/* Generated by Together */

package portaleditor.gui.editpanel;

import javax.swing.JPanel;
import javax.swing.JButton;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.BoxLayout;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import ilog.views.chart.*;
import ilog.views.chart.renderer.*;
import ilog.views.chart.data.*;
import ilog.views.chart.event.*;
import ilog.views.chart.interactor.*;
import ilog.views.chart.util.*;



public class EditPanel extends JPanel {
	

    public EditPanel() {
		// call base class constructor
        super();
        this.setLayout( new BorderLayout() );
        this.setPreferredSize( new Dimension(1024,700) );
        this.setMinimumSize( new Dimension(1024,700) );

        // create new TWD display
        JPanel	boundingPanel = new JPanel();
        boundingPanel.setLayout( new BorderLayout() );
        // create border
        boundingPanel.setBorder( BorderFactory.createTitledBorder("TWD") );
        boundingPanel.setPreferredSize( new Dimension(1024,700) );
        boundingPanel.setMinimumSize( new Dimension(1024,700) );

		try {
			lnkScreen = new IllegalJViewsPortalPanel();
        }	catch( Exception e ) {
            System.out.println( "Unable to initiate ILOG TWD screen" );
        }
       	boundingPanel.add( lnkScreen, BorderLayout.CENTER );
        this.add( boundingPanel, BorderLayout.CENTER );

		// create railsegment selection buttons panel
        railsegmentSelectionButtonsPanel = new JPanel();
        railsegmentSelectionButtonsPanel.setLayout( new FlowLayout() );

    /*    JScrollPane scrollpane = new JScrollPane( railsegmentSelectionButtonsPanel );
        scrollpane.setPreferredSize( new Dimension( 1024, 35 ) );
        scrollpane.setMinimumSize( new Dimension( 1024, 35 ) );
        scrollpane.setMaximumSize( new Dimension( 1024, 35 ) );
        scrollpane.setSize( new Dimension( 1024, 35 ) );
        this.add( scrollpane, BorderLayout.SOUTH );
*/
	}



	public void scroll( int direction ) {
        lnkScreen.scroll( direction );
    }

    private IllegalJViewsPortalPanel 	lnkScreen = null;
    private JPanel 			railsegmentSelectionButtonsPanel = null;
}
