/* Generated by Together */

package portaleditor.gui.editpanel;
import ilog.views.chart.IlvChartRenderer;
import ilog.views.chart.data.IlvDataSet;
import ilog.views.chart.renderer.IlvPolylineChartRenderer;
import ilog.views.chart.graphic.IlvDataLabelAnnotation;
import ilog.views.chart.*;

public class PortalPolylineChartRenderer extends IlvPolylineChartRenderer {

	private IlvStyle 	style = null;
	
	public PortalPolylineChartRenderer(IlvStyle style) {
		super();
		this.style = style;
	}

	public PortalPolylineChartRenderer() {
		super();
		this.style = new IlvStyle( 1.0f, IlvColor.limeGreen );
	}

   	public  IlvChartRenderer createChild(IlvDataSet ilvDataSet) {
		PortalSingleChartRenderer childRenderer = new PortalSingleChartRenderer( style );

        // !! Use IlvLabelRenderer to create some colours and stuff, set this
        // renderer to IlvDataLabelAnnotation constructor.
        IlvDataLabelAnnotation ilvDataLabelAnnotation = new IlvDataLabelAnnotation();
		childRenderer.setAnnotation( ilvDataSet, 0, ilvDataLabelAnnotation );
        return childRenderer;
   	}

}
