/* Generated by Together */

package portaleditor.gui.editpanel;

import ilog.views.chart.renderer.*;
import ilog.views.chart.IlvDisplayPoint;
import ilog.views.chart.data.*;
import ilog.views.chart.IlvStyle;
import java.awt.Point;
import java.awt.Dimension;

public class PortalSingleChartRenderer extends IlvSinglePolylineRenderer {
	private final static double LABEL_LOCATION_OFFSET = 10;

	public PortalSingleChartRenderer() {
        super();
    }

	public PortalSingleChartRenderer( IlvStyle ilvStyle ) {
        super( ilvStyle );
    }

	public String computeDataLabel(IlvDataSetPoint ilvDataSetPoint) {
//		IlvDataSet ilvDataSet = ilvDataSetPoint.getDataSet();
		String returnedLabel = "";//ilvDataSet.getName();
//        Traject traject = (Traject) ilvDataSet.getProperty( "traject" );
        return null;
    }

/*    public Point computeDataLabelLocation(IlvDisplayPoint ilvDisplayPoint, Dimension dimension){
		double		offset     	= -(dimension.getWidth() + LABEL_LOCATION_OFFSET);
		IlvDataSet 	ilvDataSet 	= ilvDisplayPoint.getDataSet();

		if( ilvDataSet.getDataCount() > 1 ) {
            // get first and second x positions
			double point1x = ilvDataSet.getXData(0);
			double point2x = ilvDataSet.getXData(1);

			// if point 2 smaller than point 1 this trains orientation on screen
            // is left ways
            if( point2x < point1x ) {
				offset = LABEL_LOCATION_OFFSET;
            }
        }

        return new Point((int) (ilvDisplayPoint.getXCoord() + offset), (int) ilvDisplayPoint.getYCoord());
    }
*/
}
