/* Generated by Together */

package portaleditor.gui.editpanel;

import java.awt.event.AdjustmentListener;
import java.awt.event.AdjustmentEvent;
import ilog.views.chart.interactor.*;

public class ScrollbarYListener implements AdjustmentListener {
	private int 					previousValue 					= 0;
	private YAxisScrollInteractor 	inversedChartScrollInteractor	= null;

	public ScrollbarYListener( int initialScrollValue, YAxisScrollInteractor inversedChartScrollInteractor ) {
        this.previousValue = initialScrollValue;
        this.inversedChartScrollInteractor = inversedChartScrollInteractor;
    }

	public void	setPreviousValue( int previousValue ) {
        this.previousValue = previousValue;
    }

	public int	getPreviousValue() {
        return previousValue;
    }

	public void adjustmentValueChanged(AdjustmentEvent ae) {
		int direction = 0;
		int deltaValue = ae.getValue() - previousValue;
		if( deltaValue != 0 ) {
			if( deltaValue < 0 ) {
				direction = IlvChartScrollInteractor.POSITIVE_DIR;
			} else {
				direction = IlvChartScrollInteractor.NEGATIVE_DIR;
			}
			inversedChartScrollInteractor.setStep(Math.abs(deltaValue));
			inversedChartScrollInteractor.scroll( direction );
//			for( int scrollCnt=0; scrollCnt<Math.abs(deltaValue); scrollCnt++ ) {
//				inversedChartScrollInteractor.scroll( direction );
//			}
			previousValue = ae.getValue();
		}

	}

}
