/* Generated by Together */

package portaleditor.gui.editpanel;

import ilog.views.chart.interactor.IlvChartYScrollInteractor;


public class YAxisScrollInteractor extends IlvChartYScrollInteractor {

	public YAxisScrollInteractor(int yAxisIndex, int negativeDirKey, int positiveDirKey, int step) {
        super(yAxisIndex, negativeDirKey, positiveDirKey, step);
    }

    public void scroll( int direction ) {
        super.scroll( direction );
    }
}
