/* Generated by Together */

package portaleditor.gui.editpanel;

import ilog.views.chart.data.IlvDataSet;
import ilog.views.chart.data.IlvDefaultDataSource;
import ilog.views.chart.interactor.IlvChartHighlightInteractor;
import ilog.views.chart.IlvDisplayPoint;
import ilog.views.chart.IlvDoublePoint;

import java.awt.event.MouseEvent;

public class ZoomInteractor extends IlvChartHighlightInteractor {
	private Zoomable  					zoomable	= null;
	private IlvDefaultDataSource 		selectedTrainDataSource = null;
	private IlvDefaultDataSource 		allTrainsDataSource = null;
	
    public ZoomInteractor(Zoomable  zoomable ) {
		this.zoomable = zoomable;
        this.setPickingMode( this.ITEM_PICKING );
    }

	public void doIt(IlvDisplayPoint highlightedPoint, boolean isHighlighted, java.awt.event.MouseEvent me) {
        if ( me.getID() == MouseEvent.MOUSE_CLICKED ) {
	        this.zoom(me);
        }
    }

 	public void processMouseEvent(java.awt.event.MouseEvent me) {
		super.processMouseEvent(me);
        if ( me.getID() == MouseEvent.MOUSE_CLICKED ) {
			IlvDisplayPoint	displayPoint = this.getHighlightedPoint();

    	    this.zoom(me);
        }
 	}

 	public void processMouseMotionEvent(java.awt.event.MouseEvent me) {
		super.processMouseMotionEvent(me);
        if ( me.getID() == MouseEvent.MOUSE_CLICKED ) {
			IlvDisplayPoint	displayPoint = this.getHighlightedPoint();

    	    this.zoom(me);
        }
 	}

	public void zoom(java.awt.event.MouseEvent me) {
		// check if point selected
    	if ( (me != null) && (zoomable != null) ) {
    		// convert to datapoint
			IlvDoublePoint dataPoint = this.getData(me);

    		zoomable.zoom( dataPoint.x, dataPoint.y );
    	}
	
    }
}
