/* Generated by Together */

package portaleditor.gui;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JPanel;

import portaleditor.gui.editpanel.EditPanel;


public class MainScreenPanel extends JPanel {

    public MainScreenPanel() {
		// call base class constructor
        super();
        this.setLayout( new BorderLayout() );
		this.setBounds( 0, 0, 1020, 768 );
        this.setPreferredSize( new Dimension(1020,768) );
        this.setMinimumSize( new Dimension(1020,768) );
        this.setSize( new Dimension(1020,768) );


		// create parent frame
        emplacementFrame = new JFrame("Portal Edit");
		emplacementPanel = new EditPanel();

        // implement 'kill' button
		emplacementFrame.addWindowListener( new WindowAdapter() {
            
            public void windowClosing(WindowEvent we) {
				showEmplacementFrame(false);    
				System.exit(0);        	
            }

            public void windowClosed(WindowEvent we) {
            }

        }  );

		emplacementFrame.getContentPane().setLayout( new BorderLayout() );
        emplacementFrame.getContentPane().add( emplacementPanel, BorderLayout.CENTER );
		emplacementFrame.setBounds( 0, 0, 1020, 700 );
		emplacementFrame.setSize( new Dimension( 1020, 700 ) );

		showEmplacementFrame(true);
	}

	public static void main( String[] args ) {
		MainScreenPanel p = new MainScreenPanel();
		
		
			
	}

	public MainScreenPanel( boolean showTBTEditorFrame ) {
		this();
		
	}
	
	public void setBusy( boolean busy ) {
		if( busy ) {
			this.setCursor(waitCursor);
			emplacementPanel.setCursor(waitCursor);	
			
		} else {
			this.setCursor(normalCursor);
			emplacementPanel.setCursor(normalCursor);	
		}
	}


	public void showEmplacementFrame(boolean show) {
		if( show ) {
			emplacementFrame.pack();
	        emplacementFrame.setVisible( true );
	        emplacementFrame.show();
		}	else {
	        emplacementFrame.hide();
		}			
	
	}


	/**
	 * Returns the emplacementPanel.
	 * @return EmplacementPanel
	 */
	public EditPanel getEmplacementPanel() {
		return emplacementPanel;
	}

	/**
	 * Sets the emplacementPanel.
	 * @param emplacementPanel The emplacementPanel to set
	 */
	public void setEmplacementPanel(EditPanel emplacementPanel) {
		this.emplacementPanel = emplacementPanel;
	}


	private EditPanel				emplacementPanel;	

	private JFrame 				emplacementFrame;	
	
	private final Cursor 			waitCursor   = new Cursor(Cursor.WAIT_CURSOR);
	private final Cursor 			normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);


}
